version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - ENV=development
    container_name: malaga
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80